DEL /F /Q C:\Windows\System32\ie4uinit.exe
DEL /F /Q C:\Windows\WinSxS\amd64_microsoft-windows-ie-setup-support_31bf3856ad364e35_11.0.18362.1_none_cc1f9ff8468b9625\ie4uinit.exe
DEL /F /Q C:\Windows\System32\en-US\ie4uinit.exe.mui
DEL /F /Q C:\Windows\WinSxS\amd64_microsoft-windows-i..p-support.resources_31bf3856ad364e35_11.0.18362.1_en-us_a560162739cc692c\ie4uinit.exe.mui
DEL /F /Q C:\Windows\System32\ie4ushowIE.exe
DEL /F /Q C:\Windows\WinSxS\amd64_microsoft-windows-ie-setup-support_31bf3856ad364e35_11.0.18362.1_none_cc1f9ff8468b9625\ie4ushowIE.exe
DEL /F /Q C:\Windows\System32\F12\IEChooser.exe
DEL /F /Q C:\Windows\SysWOW64\F12\IEChooser.exe
DEL /F /Q C:\Windows\WinSxS\amd64_microsoft-windows-ie-iechooser_31bf3856ad364e35_11.0.18362.1_none_f6c800dde24e5823\IEChooser.exe
DEL /F /Q C:\Windows\WinSxS\x86_microsoft-windows-ie-iechooser_31bf3856ad364e35_11.0.18362.1_none_9aa9655a29f0e6ed\IEChooser.exe
DEL /F /Q C:\Windows\System32\F12\en-US\IEChooser.exe.mui
DEL /F /Q C:\Windows\SysWOW64\F12\en-US\IEChooser.exe.mui
DEL /F /Q C:\Windows\WinSxS\amd64_microsoft-windows-ie-iechooser.resources_31bf3856ad364e35_11.0.18362.1_en-us_c2002d7d0bf68e92\IEChooser.exe.mui
DEL /F /Q C:\Windows\WinSxS\x86_microsoft-windows-ie-iechooser.resources_31bf3856ad364e35_11.0.18362.1_en-us_65e191f953991d5c\IEChooser.exe.mui
DEL /F /Q C:\Program Files\Internet Explorer\iediagcmd.exe
DEL /F /Q C:\Windows\WinSxS\amd64_microsoft-windows-ie-iediag_31bf3856ad364e35_11.0.18362.1_none_1d2f17d07963b2dd\iediagcmd.exe
DEL /F /Q C:\Program Files (x86)\Internet Explorer\ieinstal.exe
DEL /F /Q C:\Program Files\Internet Explorer\ieinstal.exe
DEL /F /Q C:\Windows\WinSxS\amd64_microsoft-windows-ieinstal_31bf3856ad364e35_11.0.18362.1_none_eeeac3f279b4aa38\ieinstal.exe
DEL /F /Q C:\Windows\WinSxS\x86_microsoft-windows-ieinstal_31bf3856ad364e35_11.0.18362.1_none_92cc286ec1573902\ieinstal.exe
DEL /F /Q C:\Program Files (x86)\Internet Explorer\en-US\ieinstal.exe.mui
DEL /F /Q C:\Program Files\Internet Explorer\en-US\ieinstal.exe.mui
DEL /F /Q C:\Windows\WinSxS\amd64_microsoft-windows-ieinstal.resources_31bf3856ad364e35_11.0.18362.1_en-us_5c4b7509f2fcc7d3\ieinstal.exe.mui
DEL /F /Q C:\Windows\WinSxS\x86_microsoft-windows-ieinstal.resources_31bf3856ad364e35_11.0.18362.1_en-us_002cd9863a9f569d\ieinstal.exe.mui
DEL /F /Q C:\Program Files (x86)\Internet Explorer\ielowutil.exe
DEL /F /Q C:\Program Files\Internet Explorer\ielowutil.exe
DEL /F /Q C:\Windows\WinSxS\amd64_microsoft-windows-ie-ielowutil_31bf3856ad364e35_11.0.18362.1_none_0cc4f6fa594d06e2\ielowutil.exe
DEL /F /Q C:\Windows\WinSxS\x86_microsoft-windows-ie-ielowutil_31bf3856ad364e35_11.0.18362.1_none_b0a65b76a0ef95ac\ielowutil.exe
DEL /F /Q C:\Windows\System32\ieUnatt.exe
DEL /F /Q C:\Windows\SysWOW64\ieUnatt.exe
DEL /F /Q C:\Windows\WinSxS\amd64_microsoft-windows-ie-internetexplorer_31bf3856ad364e35_11.0.18362.1_none_35b0eadd0210cd80\ieUnatt.exe
DEL /F /Q C:\Windows\WinSxS\wow64_microsoft-windows-ie-internetexplorer_31bf3856ad364e35_11.0.18362.1_none_4005952f36718f7b\ieUnatt.exe
DEL /F /Q C:\Windows\System32\en-US\ieunatt.exe.mui
DEL /F /Q C:\Windows\SysWOW64\en-US\ieunatt.exe.mui
DEL /F /Q C:\Windows\WinSxS\amd64_microsoft-windows-i..texplorer.resources_31bf3856ad364e35_11.0.18362.1_en-us_43db5dea3cd7b31b\ieunatt.exe.mui
DEL /F /Q C:\Windows\WinSxS\wow64_microsoft-windows-i..texplorer.resources_31bf3856ad364e35_11.0.18362.1_en-us_4e30083c71387516\ieunatt.exe.mui
DEL /F /Q C:\Program Files (x86)\Internet Explorer\iexplore.exe
DEL /F /Q C:\Program Files\Internet Explorer\iexplore.exe
DEL /F /Q C:\Windows\WinSxS\amd64_microsoft-windows-i..etexplorer-optional_31bf3856ad364e35_11.0.18362.1_none_9f05472d95d8148b\iexplore.exe
DEL /F /Q C:\Windows\WinSxS\wow64_microsoft-windows-i..etexplorer-optional_31bf3856ad364e35_11.0.18362.1_none_a959f17fca38d686\iexplore.exe
DEL /F /Q C:\Program Files (x86)\Internet Explorer\en-US\iexplore.exe.mui
DEL /F /Q C:\Program Files\Internet Explorer\en-US\iexplore.exe.mui
DEL /F /Q C:\Windows\WinSxS\amd64_microsoft-windows-i..-optional.resources_31bf3856ad364e35_11.0.18362.1_en-us_98b1dca4cd855572\iexplore.exe.mui
DEL /F /Q C:\Windows\WinSxS\wow64_microsoft-windows-i..-optional.resources_31bf3856ad364e35_11.0.18362.1_en-us_a30686f701e6176d\iexplore.exe.mui
DEL /F /Q C:\Windows\System32\iexpress.exe
DEL /F /Q C:\Windows\SysWOW64\iexpress.exe
DEL /F /Q C:\Windows\WinSxS\amd64_microsoft-windows-ie-iexpress_31bf3856ad364e35_11.0.18362.1_none_6acac7b526c43e97\iexpress.exe
DEL /F /Q C:\Windows\WinSxS\x86_microsoft-windows-ie-iexpress_31bf3856ad364e35_11.0.18362.1_none_0eac2c316e66cd61\iexpress.exe
DEL /F /Q C:\Windows\System32\en-US\iexpress.exe.mui
DEL /F /Q C:\Windows\SysWOW64\en-US\iexpress.exe.mui
DEL /F /Q C:\Windows\WinSxS\amd64_microsoft-windows-ie-iexpress.resources_31bf3856ad364e35_11.0.18362.1_en-us_29d470870ce5860c\iexpress.exe.mui
DEL /F /Q C:\Windows\WinSxS\x86_microsoft-windows-ie-iexpress.resources_31bf3856ad364e35_11.0.18362.1_en-us_cdb5d503548814d6\iexpress.exe.mui
RD /S /Q C:\Windows\WinSxS\amd64_microsoft-windows-ie-setup-support_31bf3856ad364e35_11.0.18362.1_none_cc1f9ff8468b9625
RD /S /Q C:\WINDOWS\WINSXS\wow64_microsoft-windows-ie-setup-support_31bf3856ad364e35_11.0.18362.1_none_d6744a4a7aec5820
DEL /F /Q C:\WINDOWS\WINSXS\MANIFESTS\wow64_microsoft-windows-ie-setup-support_31bf3856ad364e35_11.0.18362.1_none_d6744a4a7aec5820.MANIFEST
DEL /F /Q C:\Windows\WinSxS\MANIFESTS\amd64_microsoft-windows-ie-setup-support_31bf3856ad364e35_11.0.18362.1_none_cc1f9ff8468b9625.MANIFEST
RD /S /Q C:\Windows\WinSxS\amd64_microsoft-windows-i..p-support.resources_31bf3856ad364e35_11.0.18362.1_en-us_a560162739cc692c
DEL /F /Q C:\Windows\WinSxS\MANIFESTS\amd64_microsoft-windows-i..p-support.resources_31bf3856ad364e35_11.0.18362.1_en-us_a560162739cc692c.MANIFEST
RD /S /Q C:\WINDOWS\WINSXS\wow64_microsoft-windows-i..p-support.resources_31bf3856ad364e35_11.0.18362.1_en-us_afb4c0796e2d2b27
DEL /F /Q C:\WINDOWS\WINSXS\MANIFESTS\wow64_microsoft-windows-i..p-support.resources_31bf3856ad364e35_11.0.18362.1_en-us_afb4c0796e2d2b27.MANIFEST
RD /S /Q C:\Windows\WinSxS\amd64_microsoft-windows-ie-setup-support_31bf3856ad364e35_11.0.18362.1_none_cc1f9ff8468b9625
DEL /F /Q C:\Windows\WinSxS\MANIFESTS\amd64_microsoft-windows-ie-setup-support_31bf3856ad364e35_11.0.18362.1_none_cc1f9ff8468b9625.MANIFEST
RD /S /Q C:\Windows\WinSxS\amd64_microsoft-windows-ie-iechooser_31bf3856ad364e35_11.0.18362.1_none_f6c800dde24e5823
DEL /F /Q C:\Windows\WinSxS\MANIFESTS\amd64_microsoft-windows-ie-iechooser_31bf3856ad364e35_11.0.18362.1_none_f6c800dde24e5823.MANIFEST
RD /S /Q C:\Windows\WinSxS\x86_microsoft-windows-ie-iechooser_31bf3856ad364e35_11.0.18362.1_none_9aa9655a29f0e6ed
DEL /F /Q C:\Windows\WinSxS\MANIFESTS\x86_microsoft-windows-ie-iechooser_31bf3856ad364e35_11.0.18362.1_none_9aa9655a29f0e6ed.MANIFEST
RD /S /Q C:\Windows\WinSxS\x86_microsoft-windows-ie-f12tab_31bf3856ad364e35_11.0.18362.1_none_21d88b3f49ef0d0e
DEL /F /Q C:\Windows\WinSxS\MANIFESTS\x86_microsoft-windows-ie-f12tab_31bf3856ad364e35_11.0.18362.1_none_21d88b3f49ef0d0e.MANIFEST
RD /S /Q C:\Windows\WinSxS\x86_microsoft-windows-ie-f12script_31bf3856ad364e35_11.0.18362.1_none_bba32ece6da86e00
DEL /F /Q C:\Windows\WinSxS\MANIFESTS\x86_microsoft-windows-ie-f12script_31bf3856ad364e35_11.0.18362.1_none_bba32ece6da86e00.MANIFEST
RD /S /Q C:\Windows\WinSxS\x86_microsoft-windows-ie-f12script.resources_31bf3856ad364e35_11.0.18362.1_en-us_2909a192f15df0a1
DEL /F /Q C:\Windows\WinSxS\MANIFESTS\x86_microsoft-windows-ie-f12script.resources_31bf3856ad364e35_11.0.18362.1_en-us_2909a192f15df0a1.MANIFEST
RD /S /Q C:\Windows\WinSxS\x86_microsoft-windows-ie-f12platform_31bf3856ad364e35_11.0.18362.1_none_fa712454d55d49c0
DEL /F /Q C:\Windows\WinSxS\MANIFESTS\x86_microsoft-windows-ie-f12platform_31bf3856ad364e35_11.0.18362.1_none_fa712454d55d49c0.MANIFEST
RD /S /Q C:\Windows\WinSxS\x86_microsoft-windows-ie-f12platform2_31bf3856ad364e35_11.0.18362.1_none_71ec546d08a30fb6
DEL /F /Q C:\Windows\WinSxS\MANIFESTS\x86_microsoft-windows-ie-f12platform2_31bf3856ad364e35_11.0.18362.1_none_71ec546d08a30fb6.MANIFEST
RD /S /Q C:\Windows\WinSxS\x86_microsoft-windows-ie-f12appframe_31bf3856ad364e35_11.0.18362.1_none_6e8273a82461b585
DEL /F /Q C:\Windows\WinSxS\MANIFESTS\x86_microsoft-windows-ie-f12appframe_31bf3856ad364e35_11.0.18362.1_none_6e8273a82461b585.MANIFEST
RD /S /Q C:\Windows\WinSxS\x86_microsoft-windows-ie-f12app_31bf3856ad364e35_11.0.18362.1_none_18d7580d4fc6bcea
DEL /F /Q C:\Windows\WinSxS\x86_microsoft-windows-ie-f12app_31bf3856ad364e35_11.0.18362.1_none_18d7580d4fc6bcea.MANIFEST
RD /S /Q C:\Windows\WinSxS\x86_microsoft-windows-i..2platform.resources_31bf3856ad364e35_11.0.18362.1_en-us_5ec5681afde8205b
DEL /F /Q C:\Windows\WinSxS\MANIFESTS\x86_microsoft-windows-i..2platform.resources_31bf3856ad364e35_11.0.18362.1_en-us_5ec5681afde8205b.MANIFEST
RD /S /Q C:\Windows\WinSxS\x86_microsoft-windows-i..2platform.resources_31bf3856ad364e35_11.0.18362.1_en-us_5ec5681afde8205b
DEL /F /Q C:\Windows\WinSxS\MANIFESTS\x86_microsoft-windows-i..2platform.resources_31bf3856ad364e35_11.0.18362.1_en-us_5ec5681afde8205b.MANIFEST
RD /S /Q C:\Windows\WinSxS\x86_microsoft-windows-f12-f12appframe2_31bf3856ad364e35_11.0.18362.1_none_a728a52bd82f7738
DEL /F /Q C:\Windows\WinSxS\MANIFESTS\x86_microsoft-windows-f12-f12appframe2_31bf3856ad364e35_11.0.18362.1_none_a728a52bd82f7738.MANIFEST
RD /S /Q C:\Windows\WinSxS\amd64_microsoft-windows-m..oolsclient.appxmain_31bf3856ad364e35_10.0.18362.1_none_92399784a690c434
DEL /F /Q C:\Windows\WinSxS\MANIFESTS\amd64_microsoft-windows-m..oolsclient.appxmain_31bf3856ad364e35_10.0.18362.1_none_92399784a690c434.MANIFEST
RD /S /Q C:\Windows\WinSxS\amd64_microsoft-windows-ie-f12tab_31bf3856ad364e35_11.0.18362.1_none_7df726c3024c7e44
DEL /F /Q C:\Windows\WinSxS\MANIFESTS\amd64_microsoft-windows-ie-f12tab_31bf3856ad364e35_11.0.18362.1_none_7df726c3024c7e44.MANIFEST
RD /S /Q C:\Windows\WinSxS\amd64_microsoft-windows-ie-f12script_31bf3856ad364e35_11.0.18362.1_none_17c1ca522605df36
DEL /F /Q C:\Windows\WinSxS\MANIFESTS\amd64_microsoft-windows-ie-f12script_31bf3856ad364e35_11.0.18362.1_none_17c1ca522605df36.MANIFEST
RD /S /Q C:\Windows\WinSxS\amd64_microsoft-windows-ie-f12script.resources_31bf3856ad364e35_11.0.18362.1_en-us_85283d16a9bb61d7
DEL /F /Q C:\Windows\WinSxS\MANIFESTS\amd64_microsoft-windows-ie-f12script.resources_31bf3856ad364e35_11.0.18362.1_en-us_85283d16a9bb61d7.MANIFEST
RD /S /Q C:\Windows\WinSxS\amd64_microsoft-windows-ie-f12platform_31bf3856ad364e35_11.0.18362.1_none_568fbfd88dbabaf6
DEL /F /Q C:\Windows\WinSxS\MANIFESTS\amd64_microsoft-windows-ie-f12platform_31bf3856ad364e35_11.0.18362.1_none_568fbfd88dbabaf6.MANIFEST
RD /S /Q C:\Windows\WinSxS\amd64_microsoft-windows-ie-f12platform2_31bf3856ad364e35_11.0.18362.1_none_ce0aeff0c10080ec
DEL /F /Q C:\Windows\WinSxS\MANIFESTS\amd64_microsoft-windows-ie-f12platform2_31bf3856ad364e35_11.0.18362.1_none_ce0aeff0c10080ec.MANIFEST
RD /S /Q C:\Windows\WinSxS\amd64_microsoft-windows-ie-f12appframe_31bf3856ad364e35_11.0.18362.1_none_caa10f2bdcbf26bb
DEL /F /Q C:\Windows\WinSxS\MANIFESTS\amd64_microsoft-windows-ie-f12appframe_31bf3856ad364e35_11.0.18362.1_none_caa10f2bdcbf26bb.MANIFEST
RD /S /Q C:\Windows\WinSxS\amd64_microsoft-windows-ie-f12app_31bf3856ad364e35_11.0.18362.1_none_74f5f39108242e20
DEL /F /Q C:\Windows\WinSxS\WINSXS\amd64_microsoft-windows-ie-f12app_31bf3856ad364e35_11.0.18362.1_none_74f5f39108242e20.MANIFEST
RD /S /Q C:\Windows\WinSxS\amd64_microsoft-windows-i..platform2.resources_31bf3856ad364e35_11.0.18362.1_en-us_20aa5e8ff35ac32f
DEL /F /Q C:\Windows\WinSxS\MANIFESTS\amd64_microsoft-windows-i..platform2.resources_31bf3856ad364e35_11.0.18362.1_en-us_20aa5e8ff35ac32f.MANIFEST
RD /S /Q C:\Windows\WinSxS\amd64_microsoft-windows-i..2platform.resources_31bf3856ad364e35_11.0.18362.1_en-us_bae4039eb6459191
DEL /F /Q C:\Windows\WinSxS\MANIFESTS\amd64_microsoft-windows-i..2platform.resources_31bf3856ad364e35_11.0.18362.1_en-us_bae4039eb6459191.MANIFEST
RD /S /Q C:\Windows\WinSxS\amd64_microsoft-windows-f12-f12appframe2_31bf3856ad364e35_11.0.18362.1_none_034740af908ce86e
DEL /F /Q C:\Windows\WinSxS\MANIFESTS\amd64_microsoft-windows-f12-f12appframe2_31bf3856ad364e35_11.0.18362.1_none_034740af908ce86e.MANIFEST
RD /S /Q C:\Windows\SystemApps\Microsoft.MicrosoftEdgeDevToolsClient_8wekyb3d8bbwe
EXIT