reg delete HKEY_CLASSES_ROOT\CLSID\{A6FF50C0-56C0-71CA-5732-BED303A59628} /f
REG DELETE HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Users/Default/ntuser.dat\Software\Microsoft\Windows\CurrentVersion\PenWorkspace\Notes /VA /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Users/Default/ntuser.dat\Software\Microsoft\Windows NT\CurrentVersion\TileDataModel\NewAUMIDs\Microsoft.SkypeApp_kzf8qxf38zg5c!App" /F
EXIT