reg delete HKEY_CLASSES_ROOT\CLSID\{A6FF50C0-56C0-71CA-5732-BED303A59628} /f
RD /S /Q C:\Windows\WinSxS\amd64_microsoft-windows-s..lers-onedrivebackup_31bf3856ad364e35_10.0.18362.1_none_7a1514e6a782aaec
RD /S /Q C:\Windows\WinSxS\amd64_microsoft-windows-settingsync-onedrive_31bf3856ad364e35_10.0.18362.1_none_a1aaa650be85e000
RD /S /Q C:\Windows\WinSxS\wow64_microsoft-windows-onedrive-setup_31bf3856ad364e35_10.0.18362.1_none_01f25b79d7a97c4b
RD /S /Q C:\Windows\WinSxS\wow64_microsoft-windows-settingsync-onedrive_31bf3856ad364e35_10.0.18362.1_none_abff50a2f2e6a1fb
DEL /F /Q C:\USERS\DEFAULTUSER0\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\OneDrive.lnk
DEL /F /Q C:\WINDOWS\SYSTEM32\CONFIG\SYSTEMPROFILE\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\OneDrive.lnk
DEL /F /Q C:\USERS\TEMP\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\OneDrive.lnk
DEL /F /Q C:\USERS\SYSTEM\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\OneDrive.lnk
DEL /F /Q C:\USERS\ADMINISTRATOR\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\OneDrive.lnk
DEL /F /Q C:\USERS\JUGADOR\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\OneDrive.lnk
DEL /F /Q C:\USERS\GAMER\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\OneDrive.lnk
DEL /F /Q C:\USERS\Default\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\OneDrive.lnk
DEL /F /Q C:\Windows\servicing\Packages\Microsoft-Windows-OneDrive-Setup-Package~31bf3856ad364e35~amd64~en-US~10.0.18362.1.cat
DEL /F /Q C:\Windows\servicing\Packages\Microsoft-Windows-OneDrive-Setup-Package~31bf3856ad364e35~amd64~en-US~10.0.18362.1.mum
DEL /F /Q C:\Windows\servicing\Packages\Microsoft-Windows-OneDrive-Setup-Package~31bf3856ad364e35~amd64~~10.0.18362.1.cat
DEL /F /Q C:\Windows\servicing\Packages\Microsoft-Windows-OneDrive-Setup-Package~31bf3856ad364e35~amd64~~10.0.18362.1.mum
DEL /F /Q C:\Windows\servicing\Packages\Microsoft-Windows-OneDrive-Setup-WOW64-Package~31bf3856ad364e35~amd64~en-US~10.0.18362.1.cat
DEL /F /Q C:\Windows\servicing\Packages\Microsoft-Windows-OneDrive-Setup-WOW64-Package~31bf3856ad364e35~amd64~en-US~10.0.18362.1.mum
DEL /F /Q C:\Windows\servicing\Packages\Microsoft-Windows-OneDrive-Setup-WOW64-Package~31bf3856ad364e35~amd64~~10.0.18362.1.cat
DEL /F /Q C:\Windows\servicing\Packages\Microsoft-Windows-OneDrive-Setup-WOW64-Package~31bf3856ad364e35~amd64~~10.0.18362.1.mum
DEL /F /Q C:\Windows\System32\OneDriveSettingSyncProvider.dll
DEL /F /Q C:\Windows\System32\SettingsHandlers_OneDriveBackup.dll
DEL /F /Q C:\Windows\System32\CatRoot\{F750E6C3-38EE-11D1-85E5-00C04FC295EE}\Microsoft-Windows-OneDrive-Setup-Package~31bf3856ad364e35~amd64~en-US~10.0.18362.1.cat
DEL /F /Q C:\Windows\System32\CatRoot\{F750E6C3-38EE-11D1-85E5-00C04FC295EE}\Microsoft-Windows-OneDrive-Setup-Package~31bf3856ad364e35~amd64~~10.0.18362.1.cat
DEL /F /Q C:\Windows\System32\CatRoot\{F750E6C3-38EE-11D1-85E5-00C04FC295EE}\Microsoft-Windows-OneDrive-Setup-WOW64-Package~31bf3856ad364e35~amd64~en-US~10.0.18362.1.cat
DEL /F /Q C:\Windows\System32\CatRoot\{F750E6C3-38EE-11D1-85E5-00C04FC295EE}\Microsoft-Windows-OneDrive-Setup-WOW64-Package~31bf3856ad364e35~amd64~~10.0.18362.1.cat
DEL /F /Q C:\Windows\System32\en-US\SettingsHandlers_OneDriveBackup.dll.mui
DEL /F /Q C:\Windows\SysWOW64\OneDrive.ico
DEL /F /Q C:\Windows\SysWOW64\OneDriveSettingSyncProvider.dll
DEL /F /Q C:\Windows\SysWOW64\OneDriveSetup.exe
DEL /F /Q C:\Windows\WinSxS\amd64_microsoft-windows-s..ivebackup.resources_31bf3856ad364e35_10.0.18362.1_en-us_fec40bd3a1a43b31\SettingsHandlers_OneDriveBackup.dll.mui
DEL /F /Q C:\Windows\WinSxS\Manifests\amd64_microsoft-windows-onedrive-setup_31bf3856ad364e35_10.0.18362.1_none_f79db127a348ba50.manifest
DEL /F /Q C:\Windows\WinSxS\Manifests\amd64_microsoft-windows-s..lers-onedrivebackup_31bf3856ad364e35_10.0.18362.1_none_7a1514e6a782aaec.manifest
DEL /F /Q C:\Windows\WinSxS\Manifests\amd64_microsoft-windows-settingsync-onedrive_31bf3856ad364e35_10.0.18362.1_none_a1aaa650be85e000.manifest
DEL /F /Q C:\Windows\WinSxS\Manifests\wow64_microsoft-windows-onedrive-setup_31bf3856ad364e35_10.0.18362.1_none_01f25b79d7a97c4b.manifest
DEL /F /Q C:\Windows\WinSxS\Manifests\wow64_microsoft-windows-settingsync-onedrive_31bf3856ad364e35_10.0.18362.1_none_abff50a2f2e6a1fb.manifest
EXIT