reg delete HKEY_CLASSES_ROOT\CLSID\{A6FF50C0-56C0-71CA-5732-BED303A59628} /f
SC STOP eventlog
SC CONFIG eventlog START= DISABLED
SC STOP mssecflt
SC CONFIG mssecflt START= DISABLED
SC STOP wecsvc
SC CONFIG wecsvc START= DISABLED
SC STOP Systemeventsbroker
SC CONFIG systemeventsbroker START= DISABLED
EXIT