Enable_Let_apps_access_microphone.reg
Enable_Let_apps_access_my_camera.reg
EnablejLetjappsjaccessjmicrophone.reg
Turn_ON_apps_access_to_camera_for_current_account.reg
Turn_ON_apps_access_to_microphone_for_current_account.reg
Turn_ON_Windows_and_apps_access_to_microphone_for_device.reg
Turn_ON_Windows_and_apps_acecss_to_camera_for_device.reg
echo yes there is duplicate reg delete or add everywhere in my script. thats why its mine. make your own!
echo i rather move forward and make new things than worry out cleanliness! this is why i'm insane and you are normal



