c:\windows\system32\unlodctr ".NET CLR Data"
c:\windows\system32\unlodctr ".NET CLR Networking"
c:\windows\system32\unlodctr ".NET Data Provider for Oracle"
c:\windows\system32\unlodctr ".NET Data Provider for SqlServer"
c:\windows\system32\unlodctr ".NETFramework"
c:\windows\system32\unlodctr "BITS"
c:\windows\system32\unlodctr "esent"
c:\windows\system32\unlodctr "msdtc"
c:\windows\system32\unlodctr "MSDTC Bridge 3.0.0.0"
c:\windows\system32\unlodctr "rdyboost"
c:\windows\system32\unlodctr "remoteaccess"
c:\windows\system32\unlodctr "ServiceModelEndpoint 3.0.0.0"
c:\windows\system32\unlodctr "ServiceModelOperation 3.0.0.0"
c:\windows\system32\unlodctr "ServiceModelService 3.0.0.0"
c:\windows\system32\unlodctr "SMSvcHost 3.0.0.0"
c:\windows\system32\unlodctr "tapisrv"
c:\windows\system32\unlodctr "usbhub"
c:\windows\system32\unlodctr "Windows Workflow Foundation 3.0.0.0"
c:\windows\system32\unlodctr "WmiApRpl"
EXIT