takeown /f c:\windows\system32\logfiles\wmi\* /r /d y
icacls c:\windows\system32\logfiles\wmi\* /grant administrators:f /t
del /f c:\windows\system32\logfiles\wmi\CloudExperienceHostOobe.etl
del /f c:\windows\system32\logfiles\wmi\CloudExperienceHostOobe.etl.000
del /f c:\windows\system32\logfiles\wmi\CloudExperienceHostOobe.etl.001
del /f c:\windows\system32\logfiles\wmi\CloudExperienceHostOobe.etl.002
del /f c:\windows\system32\logfiles\wmi\CloudExperienceHostOobe.etl.003
del /f c:\windows\system32\logfiles\wmi\CloudExperienceHostOobe.etl.004
del /f c:\windows\system32\logfiles\wmi\CloudExperienceHostOobe.etl.005
del /f c:\windows\system32\logfiles\wmi\CloudExperienceHostOobe.etl.006
del /f c:\windows\system32\logfiles\wmi\CloudExperienceHostOobe.etl.007
del /f c:\windows\system32\logfiles\wmi\CloudExperienceHostOobe.etl.008
del /f c:\windows\system32\logfiles\wmi\CloudExperienceHostOobe.etl.009
del /f c:\windows\system32\logfiles\wmi\SpoolerLogger.etl
del /f c:\windows\system32\logfiles\wmi\SpoolerLogger.etl.000
del /f c:\windows\system32\logfiles\wmi\SpoolerLogger.etl.001
del /f c:\windows\system32\logfiles\wmi\SpoolerLogger.etl.002
del /f c:\windows\system32\logfiles\wmi\SpoolerLogger.etl.003
del /f c:\windows\system32\logfiles\wmi\SpoolerLogger.etl.004
del /f c:\windows\system32\logfiles\wmi\SpoolerLogger.etl.005
del /f c:\windows\system32\logfiles\wmi\SpoolerLogger.etl.006
del /f c:\windows\system32\logfiles\wmi\SpoolerLogger.etl.007
del /f c:\windows\system32\logfiles\wmi\SpoolerLogger.etl.008
del /f c:\windows\system32\logfiles\wmi\SpoolerLogger.etl.009
nul > c:\windows\system32\logfiles\wmi\CloudExperienceHostOobe.etl
nul > c:\windows\system32\logfiles\wmi\CloudExperienceHostOobe.etl.000
nul > c:\windows\system32\logfiles\wmi\CloudExperienceHostOobe.etl.001
nul > c:\windows\system32\logfiles\wmi\CloudExperienceHostOobe.etl.002
nul > c:\windows\system32\logfiles\wmi\CloudExperienceHostOobe.etl.003
nul > c:\windows\system32\logfiles\wmi\CloudExperienceHostOobe.etl.004
nul > c:\windows\system32\logfiles\wmi\CloudExperienceHostOobe.etl.005
nul > c:\windows\system32\logfiles\wmi\CloudExperienceHostOobe.etl.006
nul > c:\windows\system32\logfiles\wmi\CloudExperienceHostOobe.etl.007
nul > c:\windows\system32\logfiles\wmi\CloudExperienceHostOobe.etl.008
nul > c:\windows\system32\logfiles\wmi\CloudExperienceHostOobe.etl.009
nul > c:\windows\system32\logfiles\wmi\SpoolerLogger.etl
nul > c:\windows\system32\logfiles\wmi\SpoolerLogger.etl.000
nul > c:\windows\system32\logfiles\wmi\SpoolerLogger.etl.001
nul > c:\windows\system32\logfiles\wmi\SpoolerLogger.etl.002
nul > c:\windows\system32\logfiles\wmi\SpoolerLogger.etl.003
nul > c:\windows\system32\logfiles\wmi\SpoolerLogger.etl.004
nul > c:\windows\system32\logfiles\wmi\SpoolerLogger.etl.005
nul > c:\windows\system32\logfiles\wmi\SpoolerLogger.etl.006
nul > c:\windows\system32\logfiles\wmi\SpoolerLogger.etl.007
nul > c:\windows\system32\logfiles\wmi\SpoolerLogger.etl.008
nul > c:\windows\system32\logfiles\wmi\SpoolerLogger.etl.009
attrib +r +s +h +i c:\windows\system32\logfiles\wmi\CloudExperienceHostOobe.etl
attrib +r +s +h +i c:\windows\system32\logfiles\wmi\CloudExperienceHostOobe.etl.000
attrib +r +s +h +i c:\windows\system32\logfiles\wmi\CloudExperienceHostOobe.etl.001
attrib +r +s +h +i c:\windows\system32\logfiles\wmi\CloudExperienceHostOobe.etl.002
attrib +r +s +h +i c:\windows\system32\logfiles\wmi\CloudExperienceHostOobe.etl.003
attrib +r +s +h +i c:\windows\system32\logfiles\wmi\CloudExperienceHostOobe.etl.004
attrib +r +s +h +i c:\windows\system32\logfiles\wmi\CloudExperienceHostOobe.etl.005
attrib +r +s +h +i c:\windows\system32\logfiles\wmi\CloudExperienceHostOobe.etl.006
attrib +r +s +h +i c:\windows\system32\logfiles\wmi\CloudExperienceHostOobe.etl.007
attrib +r +s +h +i c:\windows\system32\logfiles\wmi\CloudExperienceHostOobe.etl.008
attrib +r +s +h +i c:\windows\system32\logfiles\wmi\CloudExperienceHostOobe.etl.009
attrib +r +s +h +i c:\windows\system32\logfiles\wmi\SpoolerLogger.etl
attrib +r +s +h +i c:\windows\system32\logfiles\wmi\SpoolerLogger.etl.000
attrib +r +s +h +i c:\windows\system32\logfiles\wmi\SpoolerLogger.etl.001
attrib +r +s +h +i c:\windows\system32\logfiles\wmi\SpoolerLogger.etl.002
attrib +r +s +h +i c:\windows\system32\logfiles\wmi\SpoolerLogger.etl.003
attrib +r +s +h +i c:\windows\system32\logfiles\wmi\SpoolerLogger.etl.004
attrib +r +s +h +i c:\windows\system32\logfiles\wmi\SpoolerLogger.etl.005
attrib +r +s +h +i c:\windows\system32\logfiles\wmi\SpoolerLogger.etl.006
attrib +r +s +h +i c:\windows\system32\logfiles\wmi\SpoolerLogger.etl.007
attrib +r +s +h +i c:\windows\system32\logfiles\wmi\SpoolerLogger.etl.008
attrib +r +s +h +i c:\windows\system32\logfiles\wmi\SpoolerLogger.etl.009
exit
