c:\windows\system32\lodctr /d:".NET CLR Data"
c:\windows\system32\lodctr /d:".NET CLR Networking"
c:\windows\system32\lodctr /d:".NET CLR Networking 4.0.0.0"
c:\windows\system32\lodctr /d:".NET Data Provider for Oracle"
c:\windows\system32\lodctr /d:".NET Data Provider for SqlServer"
c:\windows\system32\lodctr /d:".NET Memory Cache 4.0"
c:\windows\system32\lodctr /d:".NETFramework"
c:\windows\system32\lodctr /d:"BITS"
c:\windows\system32\lodctr /d:"ESENT"
c:\windows\system32\lodctr /d:"Lsa"
c:\windows\system32\lodctr /d:"LSM"
c:\windows\system32\lodctr /d:"MSDTC"
c:\windows\system32\lodctr /d:"MSDTC Bridge 3.0.0.0"
c:\windows\system32\lodctr /d:"MSDTC Bridge 4.0.0.0"
c:\windows\system32\lodctr /d:"MSSCNTRS"
c:\windows\system32\lodctr /d:"PerfDisk"
c:\windows\system32\lodctr /d:"PerfNet"
c:\windows\system32\lodctr /d:"PerfOS"
c:\windows\system32\lodctr /d:"PerfProc"
c:\windows\system32\lodctr /d:"rdyboost"
c:\windows\system32\lodctr /d:"RemoteAccess"
c:\windows\system32\lodctr /d:"ServiceModelEndpoint 3.0.0.0"
c:\windows\system32\lodctr /d:"ServiceModelOperation 3.0.0.0"
c:\windows\system32\lodctr /d:"ServiceModelService 3.0.0.0"
c:\windows\system32\lodctr /d:"SMSvcHost 3.0.0.0"
c:\windows\system32\lodctr /d:"SMSvcHost 4.0.0.0"
c:\windows\system32\lodctr /d:"Spooler"
c:\windows\system32\lodctr /d:"TermService"
c:\windows\system32\lodctr /d:"UGatherer"
c:\windows\system32\lodctr /d:"UGTHRSVC"
c:\windows\system32\lodctr /d:"usbhub"
c:\windows\system32\lodctr /d:"Windows Workflow Foundation 3.0.0.0"
c:\windows\system32\lodctr /d:"Windows Workflow Foundation 4.0.0.0"
c:\windows\system32\lodctr /d:"wmiaprpl"
c:\windows\system32\lodctr /d:"tcpip"
c:\windows\system32\lodctr /d:"tapisrv"
c:\windows\system32\lodctr /d:"wsearchidxpi"
c:\windows\system32\lodctr /d:"aspnet_state"
c:\windows\system32\lodctr /d:"asp.net_4.0.30319"
c:\windows\system32\lodctr /d:"asp.net"
c:\windows\system32\lodctr /d:".netframework"
EXIT
