reg delete HKEY_CLASSES_ROOT\CLSID\{A6FF50C0-56C0-71CA-5732-BED303A59628} /f
RD /S /Q "C:\Program Files\Internet Explorer
RD /S /Q "C:\Program Files (x86)\Internet Explorer
RD /S /Q "C:\USERS\Default\AppData\Roaming\Microsoft\Internet Explorer
RD /S /Q "C:\USERS\ADMINISTRATOR\AppData\Roaming\Microsoft\Internet Explorer
RD /S /Q "C:\USERS\GAMER\AppData\Roaming\Microsoft\Internet Explorer
RD /S /Q "C:\USERS\SYSTEM\AppData\Roaming\Microsoft\Internet Explorer
RD /S /Q "C:\USERS\TEMP\AppData\Roaming\Microsoft\Internet Explorer
RD /S /Q "C:\USERS\DEFAULTUSER0\AppData\Roaming\Microsoft\Internet Explorer
RD /S /Q "C:\WINDOWS\SYSTEM32\CONFIG\SYSTEMPROFILE\AppData\Roaming\Microsoft\Internet Explorer
DEL /F /Q C:\ProgramData\Microsoft\UEV\InboxTemplates\MicrosoftInternetExplorer2013.xml
DEL /F /Q C:\ProgramData\Microsoft\UEV\InboxTemplates\MicrosoftInternetExplorer2013Backup.xml
DEL /F /Q C:\Windows\servicing\Packages\Microsoft-Windows-InternetExplorer-Optional-Package~31bf3856ad364e35~amd64~en-US~11.0.18362.1.cat
DEL /F /Q C:\Windows\servicing\Packages\Microsoft-Windows-InternetExplorer-Optional-Package~31bf3856ad364e35~amd64~~11.0.18362.1.cat
DEL /F /Q C:\Windows\servicing\Packages\Microsoft-Windows-InternetExplorer-Package-ua~31bf3856ad364e35~amd64~en-US~10.0.18362.1.cat
DEL /F /Q C:\Windows\servicing\Packages\Microsoft-Windows-InternetExplorer-Package-ua~31bf3856ad364e35~amd64~~10.0.18362.1.cat
DEL /F /Q C:\Windows\System32\CatRoot\{F750E6C3-38EE-11D1-85E5-00C04FC295EE}\Microsoft-Windows-InternetExplorer-Optional-Package~31bf3856ad364e35~amd64~en-US~11.0.18362.1.cat
DEL /F /Q C:\Windows\System32\CatRoot\{F750E6C3-38EE-11D1-85E5-00C04FC295EE}\Microsoft-Windows-InternetExplorer-Optional-Package~31bf3856ad364e35~amd64~~11.0.18362.1.cat
DEL /F /Q C:\Windows\System32\CatRoot\{F750E6C3-38EE-11D1-85E5-00C04FC295EE}\Microsoft-Windows-InternetExplorer-Package-ua~31bf3856ad364e35~amd64~en-US~10.0.18362.1.cat
DEL /F /Q C:\Windows\System32\CatRoot\{F750E6C3-38EE-11D1-85E5-00C04FC295EE}\Microsoft-Windows-InternetExplorer-Package-ua~31bf3856ad364e35~amd64~~10.0.18362.1.cat
DEL /F /Q C:\Windows\System32\migwiz\dlmanifests\Microsoft-Windows-IE-InternetExplorer-DL.man
DEL /F /Q C:\Windows\WinSxS\FileMaps\program_files_internet_explorer_a421d1bfaf856e2b.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\program_files_internet_explorer_en-us_2650c83f8a48b821.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\program_files_internet_explorer_images_970ee9acd2503f65.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\program_files_x86_internet_explorer_cafab575245eacb0.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\program_files_x86_internet_explorer_en-us_1a6a9dd9f26fbb24.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\program_files_x86_internet_explorer_images_1a72c7a5958826c4.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\users_default_appdata_roaming_microsoft_internet_explorer_quick_launch_c0ec1d6b06e5808b.cdf-ms
EXIT
