reg delete HKEY_CLASSES_ROOT\CLSID\{A6FF50C0-56C0-71CA-5732-BED303A59628} /f
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.BingWeather_4.25.20211.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.DesktopAppInstaller_2019.125.2243.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.GetHelp_10.1706.13331.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.Getstarted_7.3.20251.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.HEIFImageExtension_1.0.13472.0_x64__8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.Messaging_2019.125.32.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.Microsoft3DViewer_5.1902.20012.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.MicrosoftOfficeHub_18.1901.1141.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.MicrosoftSolitaireCollection_4.2.11280.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.MicrosoftStickyNotes_3.1.53.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.MixedReality.Portal_2000.19010.1151.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.MSPaint_2019.213.1858.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.Office.OneNote_16001.11126.20076.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.OneConnect_5.1902.361.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.People_2019.123.2346.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.Print3D_3.3.311.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.ScreenSketch_2018.1214.231.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.SkypeApp_14.35.152.0_neutral_~_kzf8qxf38zg5c /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.StorePurchaseApp_11811.1001.1813.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.VP9VideoExtensions_1.0.13333.0_x64__8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.Wallet_2.4.18324.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.WebMediaExtensions_1.0.13321.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.WebpImageExtension_1.0.12821.0_x64__8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.Windows.Photos_2019.18114.19418.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.WindowsAlarms_2019.105.629.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.WindowsCalculator_2019.105.612.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.WindowsCamera_2018.826.78.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\microsoft.windowscommunicationsapps_16005.11029.20108.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.WindowsFeedbackHub_2019.226.2324.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.WindowsMaps_2019.108.627.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.WindowsSoundRecorder_2019.105.618.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.WindowsStore_11811.1001.1813.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.Xbox.TCUI_1.23.28002.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.XboxApp_48.48.7001.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.XboxGameOverlay_1.32.17005.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.XboxGamingOverlay_2.26.14003.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.XboxIdentityProvider_12.50.6001.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.XboxSpeechToTextOverlay_1.17.29001.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.YourPhone_2018.1128.231.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.ZuneMusic_2019.18111.17311.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.ZuneVideo_2019.18111.17311.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.BingWeather_4.25.20211.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.DesktopAppInstaller_2019.125.2243.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.GetHelp_10.1706.13331.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.Getstarted_7.3.20251.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.HEIFImageExtension_1.0.13472.0_x64__8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.Messaging_2019.125.32.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.Microsoft3DViewer_5.1902.20012.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.MicrosoftOfficeHub_18.1901.1141.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.MicrosoftSolitaireCollection_4.2.11280.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.MicrosoftStickyNotes_3.1.53.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.MixedReality.Portal_2000.19010.1151.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.MSPaint_2019.213.1858.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.Office.OneNote_16001.11126.20076.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.OneConnect_5.1902.361.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.People_2019.123.2346.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.Print3D_3.3.311.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.ScreenSketch_2018.1214.231.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.SkypeApp_14.35.152.0_neutral_~_kzf8qxf38zg5c /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.StorePurchaseApp_11811.1001.1813.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.VP9VideoExtensions_1.0.13333.0_x64__8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.Wallet_2.4.18324.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.WebMediaExtensions_1.0.13321.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.WebpImageExtension_1.0.12821.0_x64__8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.Windows.Photos_2019.18114.19418.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.WindowsAlarms_2019.105.629.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.WindowsCalculator_2019.105.612.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.WindowsCamera_2018.826.78.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\microsoft.windowscommunicationsapps_16005.11029.20108.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.WindowsFeedbackHub_2019.226.2324.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.WindowsMaps_2019.108.627.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.WindowsSoundRecorder_2019.105.618.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.WindowsStore_11811.1001.1813.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.Xbox.TCUI_1.23.28002.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.XboxApp_48.48.7001.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.XboxGameOverlay_1.32.17005.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.XboxGamingOverlay_2.26.14003.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.XboxIdentityProvider_12.50.6001.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.XboxSpeechToTextOverlay_1.17.29001.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.YourPhone_2018.1128.231.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.ZuneMusic_2019.18111.17311.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Applications\Microsoft.ZuneVideo_2019.18111.17311.0_neutral_~_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Config\Microsoft.AAD.BrokerPlugin_cw5n1h2txyewy /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Config\Microsoft.BioEnrollment_cw5n1h2txyewy /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Config\Microsoft.MicrosoftEdge_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Config\Microsoft.Windows.ContentDeliveryManager_cw5n1h2txyewy /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Config\Microsoft.Windows.Cortana_cw5n1h2txyewy /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Config\Microsoft.Windows.Photos_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Config\Microsoft.Windows.TabExperienceHost_cw5n1h2txyewy /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Config\Microsoft.WindowsCamera_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Config\microsoft.windowscommunicationsapps_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Config\Microsoft.WindowsStore_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Config\Microsoft.XboxIdentityProvider_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Config\SimSecUX_cw5n1h2txyewy /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Config\Microsoft.AAD.BrokerPlugin_cw5n1h2txyewy /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Config\Microsoft.BioEnrollment_cw5n1h2txyewy /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Config\Microsoft.MicrosoftEdge_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Config\Microsoft.Windows.ContentDeliveryManager_cw5n1h2txyewy /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Config\Microsoft.Windows.Cortana_cw5n1h2txyewy /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Config\Microsoft.Windows.Photos_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Config\Microsoft.Windows.TabExperienceHost_cw5n1h2txyewy /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Config\Microsoft.WindowsCamera_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Config\microsoft.windowscommunicationsapps_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Config\Microsoft.WindowsStore_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Config\Microsoft.XboxIdentityProvider_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Config\SimSecUX_cw5n1h2txyewy /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\E2A4F912-2574-4A75-9BB0-0D023378592B_10.0.18362.1_neutral_neutral_cw5n1h2txyewy /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\F46D4000-FD22-4DB4-AC8E-4E1DDDE828FE_10.0.18362.1_neutral_neutral_cw5n1h2txyewy /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\InputApp_10.0.18362.1_neutral_neutral_cw5n1h2txyewy /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\Microsoft.AAD.BrokerPlugin_10.0.18362.1_neutral_neutral_cw5n1h2txyewy /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\Microsoft.AsyncTextService_10.0.18362.1_neutral_neutral_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\Microsoft.BioEnrollment_10.0.18362.1_neutral_neutral_cw5n1h2txyewy /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\Microsoft.CredDialogHost_10.0.18362.1_neutral_neutral_cw5n1h2txyewy /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\Microsoft.ECApp_10.0.18362.1_neutral_neutral_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\Microsoft.MicrosoftEdge_44.18362.1.0_neutral__8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\Microsoft.MicrosoftEdgeDevToolsClient_10.0.18362.1_neutral__8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\Microsoft.PPIProjection_10.0.18362.1_neutral_neutral_cw5n1h2txyewy /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\Microsoft.Win32WebViewHost_10.0.18362.1_neutral_neutral_cw5n1h2txyewy /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\Microsoft.Windows.AppRep.ChxApp_10.0.18362.1_neutral_neutral_cw5n1h2txyewy /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\Microsoft.Windows.AssignedAccessLockApp_10.0.18362.1_neutral_neutral_cw5n1h2txyewy /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\Microsoft.Windows.CallingShellApp_10.0.18362.1_neutral_neutral_cw5n1h2txyewy /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\Microsoft.Windows.CapturePicker_10.0.18362.1_neutral_neutral_cw5n1h2txyewy /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\Microsoft.Windows.ContentDeliveryManager_10.0.18362.1_neutral_neutral_cw5n1h2txyewy /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\Microsoft.Windows.Cortana_10.0.18362.1_neutral_neutral_cw5n1h2txyewy /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\Microsoft.Windows.NarratorQuickStart_10.0.18362.1_neutral_neutral_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\Microsoft.Windows.ParentalControls_10.0.18362.1_neutral_neutral_cw5n1h2txyewy /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\Microsoft.Windows.PeopleExperienceHost_10.0.18362.1_neutral_neutral_cw5n1h2txyewy /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\Microsoft.Windows.PinningConfirmationDialog_10.0.18362.1_neutral_neutral_cw5n1h2txyewy /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\Microsoft.Windows.SecHealthUI_10.0.18362.1_neutral__cw5n1h2txyewy /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\Microsoft.Windows.SecureAssessmentBrowser_10.0.18362.1_neutral_neutral_cw5n1h2txyewy /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\Microsoft.Windows.XGpuEjectDialog_10.0.18362.1_neutral_neutral_cw5n1h2txyewy /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\Microsoft.XboxGameCallableUI_10.0.18362.1_neutral_neutral_cw5n1h2txyewy /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\Windows.CBSPreview_10.0.18362.1_neutral_neutral_cw5n1h2txyewy /F
REG DELETE HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\E2A4F912-2574-4A75-9BB0-0D023378592B_10.0.18362.1_neutral_neutral_cw5n1h2txyewy /F
REG DELETE HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\F46D4000-FD22-4DB4-AC8E-4E1DDDE828FE_10.0.18362.1_neutral_neutral_cw5n1h2txyewy /F
REG DELETE HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\InputApp_10.0.18362.1_neutral_neutral_cw5n1h2txyewy /F
REG DELETE HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\Microsoft.AAD.BrokerPlugin_10.0.18362.1_neutral_neutral_cw5n1h2txyewy /F
REG DELETE HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\Microsoft.AsyncTextService_10.0.18362.1_neutral_neutral_8wekyb3d8bbwe /F
REG DELETE HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\Microsoft.BioEnrollment_10.0.18362.1_neutral_neutral_cw5n1h2txyewy /F
REG DELETE HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\Microsoft.CredDialogHost_10.0.18362.1_neutral_neutral_cw5n1h2txyewy /F
REG DELETE HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\Microsoft.ECApp_10.0.18362.1_neutral_neutral_8wekyb3d8bbwe /F
REG DELETE HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\Microsoft.MicrosoftEdge_44.18362.1.0_neutral__8wekyb3d8bbwe /F
REG DELETE HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\Microsoft.MicrosoftEdgeDevToolsClient_10.0.18362.1_neutral__8wekyb3d8bbwe /F
REG DELETE HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\Microsoft.PPIProjection_10.0.18362.1_neutral_neutral_cw5n1h2txyewy /F
REG DELETE HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\Microsoft.Win32WebViewHost_10.0.18362.1_neutral_neutral_cw5n1h2txyewy /F
REG DELETE HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\Microsoft.Windows.AppRep.ChxApp_10.0.18362.1_neutral_neutral_cw5n1h2txyewy /F
REG DELETE HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\Microsoft.Windows.AssignedAccessLockApp_10.0.18362.1_neutral_neutral_cw5n1h2txyewy /F
REG DELETE HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\Microsoft.Windows.CallingShellApp_10.0.18362.1_neutral_neutral_cw5n1h2txyewy /F
REG DELETE HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\Microsoft.Windows.CapturePicker_10.0.18362.1_neutral_neutral_cw5n1h2txyewy /F
REG DELETE HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\Microsoft.Windows.ContentDeliveryManager_10.0.18362.1_neutral_neutral_cw5n1h2txyewy /F
REG DELETE HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\Microsoft.Windows.Cortana_10.0.18362.1_neutral_neutral_cw5n1h2txyewy /F
REG DELETE HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\Microsoft.Windows.NarratorQuickStart_10.0.18362.1_neutral_neutral_8wekyb3d8bbwe /F
REG DELETE HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\Microsoft.Windows.ParentalControls_10.0.18362.1_neutral_neutral_cw5n1h2txyewy /F
REG DELETE HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\Microsoft.Windows.PeopleExperienceHost_10.0.18362.1_neutral_neutral_cw5n1h2txyewy /F
REG DELETE HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\Microsoft.Windows.PinningConfirmationDialog_10.0.18362.1_neutral_neutral_cw5n1h2txyewy /F
REG DELETE HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\Microsoft.Windows.SecHealthUI_10.0.18362.1_neutral__cw5n1h2txyewy /F
REG DELETE HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\Microsoft.Windows.SecureAssessmentBrowser_10.0.18362.1_neutral_neutral_cw5n1h2txyewy /F
REG DELETE HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\Microsoft.Windows.XGpuEjectDialog_10.0.18362.1_neutral_neutral_cw5n1h2txyewy /F
REG DELETE HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\Microsoft.XboxGameCallableUI_10.0.18362.1_neutral_neutral_cw5n1h2txyewy /F
REG DELETE HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\InboxApplications\Windows.CBSPreview_10.0.18362.1_neutral_neutral_cw5n1h2txyewy /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.Advertising.Xaml_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.BingWeather_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.GetHelp_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.Getstarted_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.HEIFImageExtension_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.Messaging_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.Microsoft3DViewer_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.MicrosoftOfficeHub_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.MicrosoftSolitaireCollection_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.MicrosoftStickyNotes_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.MixedReality.Portal_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.MSPaint_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.Office.OneNote_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.OneConnect_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.People_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.Print3D_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.ScreenSketch_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.Services.Store.Engagement_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.SkypeApp_kzf8qxf38zg5c /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.StorePurchaseApp_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.VP9VideoExtensions_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.Wallet_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.WebMediaExtensions_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.WebpImageExtension_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.Windows.Photos_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.WindowsAlarms_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.WindowsCalculator_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.WindowsCamera_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\microsoft.windowscommunicationsapps_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.WindowsFeedbackHub_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.WindowsMaps_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.WindowsSoundRecorder_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.WindowsStore_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.Xbox.TCUI_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.XboxApp_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.XboxGameOverlay_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.XboxGamingOverlay_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.XboxIdentityProvider_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.XboxSpeechToTextOverlay_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.YourPhone_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.ZuneMusic_8wekyb3d8bbwe /F
REG DELETE HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.ZuneVideo_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.Advertising.Xaml_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.BingWeather_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.GetHelp_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.Getstarted_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.HEIFImageExtension_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.Messaging_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.Microsoft3DViewer_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.MicrosoftOfficeHub_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.MicrosoftSolitaireCollection_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.MicrosoftStickyNotes_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.MixedReality.Portal_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.MSPaint_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.Office.OneNote_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.OneConnect_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.People_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.Print3D_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.ScreenSketch_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.Services.Store.Engagement_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.SkypeApp_kzf8qxf38zg5c /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.StorePurchaseApp_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.VP9VideoExtensions_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.Wallet_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.WebMediaExtensions_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.WebpImageExtension_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.Windows.Photos_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.WindowsAlarms_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.WindowsCalculator_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.WindowsCamera_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\microsoft.windowscommunicationsapps_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.WindowsFeedbackHub_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.WindowsMaps_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.WindowsSoundRecorder_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.WindowsStore_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.Xbox.TCUI_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.XboxApp_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.XboxGameOverlay_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.XboxGamingOverlay_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.XboxIdentityProvider_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.XboxSpeechToTextOverlay_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.YourPhone_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.ZuneMusic_8wekyb3d8bbwe /F
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Staged\Microsoft.ZuneVideo_8wekyb3d8bbwe /F
RD /S /Q C:\WINDOWS\WINSXS\amd64_microsoft-windows-c...appxmain.resources_31bf3856ad364e35_10.0.18362.1_en-us_31922094d751a9d
RD /S /Q C:\WINDOWS\WINSXS\amd64_microsoft-windows-c...appxmain.resources_31bf3856ad364e35_10.0.18362.1_en-us_04dd71737de73163
RD /S /Q C:\WINDOWS\WINSXS\amd64_microsoft-windows-c...appxmain.resources_31bf3856ad364e35_10.0.18362.1_en-us_4bd2b5ed01a4896f
RD /S /Q C:\WINDOWS\WINSXS\amd64_microsoft-windows-c...appxmain.resources_31bf3856ad364e35_10.0.18362.1_en-us_cd6048e16f7a6993
DEL /F /Q C:\WINDOWS\WINSXS\MANIFESTS\amd64_microsoft-windows-c...appxmain.resources_31bf3856ad364e35_10.0.18362.1_en-us_cd6048e16f7a6993.MANIFEST
DEL /F /Q C:\WINDOWS\WINSXS\MANIFESTS\C:\WINDOWS\WINSXS\amd64_microsoft-windows-c...appxmain.resources_31bf3856ad364e35_10.0.18362.1_en-us_31922094d751a9d
DEL /F /Q C:\WINDOWS\WINSXS\MANIFESTS\C:\WINDOWS\WINSXS\amd64_microsoft-windows-c...appxmain.resources_31bf3856ad364e35_10.0.18362.1_en-us_04dd71737de73163
DEL /F /Q C:\WINDOWS\WINSXS\MANIFESTS\C:\WINDOWS\WINSXS\amd64_microsoft-windows-c...appxmain.resources_31bf3856ad364e35_10.0.18362.1_en-us_4bd2b5ed01a4896f
ECHO -------
REG DELETE "HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Active Setup\MimeFeature" /V TEXT/X-VCARD /F
REG DELETE "HKLM\SOFTWARE\Microsoft\Active Setup\MimeFeature" /V TEXT/X-VCARD /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Active Setup\Installed Components\{22d6f312-b0f6-11d0-94ab-0080c74c7e95}" /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Active Setup\Installed Components\{2C7339CF-2B09-4501-B3F3-F3508C9228ED}" /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Active Setup\Installed Components\{3af36230-a269-11d1-b5bf-0000f8051515}" /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Active Setup\Installed Components\{45ea75a0-a269-11d1-b5bf-0000f8051515}" /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Active Setup\Installed Components\{4f645220-306d-11d2-995d-00c04f98bbc9}" /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Active Setup\Installed Components\{5fd399c0-a70a-11d1-9948-00c04f98bbc9}" /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Active Setup\Installed Components\{630b1da0-b465-11d1-9948-00c04f98bbc9}" /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Active Setup\Installed Components\{6BF52A52-394A-11d3-B153-00C04F79FAA6}" /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Active Setup\Installed Components\{6fab99d0-bab8-11d1-994a-00c04f98bbc9}" /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Active Setup\Installed Components\{7790769C-0471-11d2-AF11-00C04FA35D02}" /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Active Setup\Installed Components\{89820200-ECBD-11cf-8B85-00AA005B4340}" /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Active Setup\Installed Components\{89820200-ECBD-11cf-8B85-00AA005B4383}" /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Active Setup\Installed Components\{9381D8F2-0288-11D0-9501-00AA00B911A5}" /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Active Setup\Installed Components\{C9E9A340-D1F1-11D0-821E-444553540600}" /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Active Setup\Installed Components\{de5aed00-a4bf-11d1-9948-00c04f98bbc9}" /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Active Setup\Installed Components\{E92B03AB-B707-11d2-9CBD-0000F87A369E}" /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Active Setup\Installed Components\>{22d6f312-b0f6-11d0-94ab-0080c74c7e95}" /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Active Setup\Installed Components\{22d6f312-b0f6-11d0-94ab-0080c74c7e95}" /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Active Setup\Installed Components\{2C7339CF-2B09-4501-B3F3-F3508C9228ED}" /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Active Setup\Installed Components\{3af36230-a269-11d1-b5bf-0000f8051515}" /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Active Setup\Installed Components\{45ea75a0-a269-11d1-b5bf-0000f8051515}" /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Active Setup\Installed Components\{4f645220-306d-11d2-995d-00c04f98bbc9}" /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Active Setup\Installed Components\{5fd399c0-a70a-11d1-9948-00c04f98bbc9}" /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Active Setup\Installed Components\{630b1da0-b465-11d1-9948-00c04f98bbc9}" /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Active Setup\Installed Components\{6BF52A52-394A-11d3-B153-00C04F79FAA6}" /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Active Setup\Installed Components\{6fab99d0-bab8-11d1-994a-00c04f98bbc9}" /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Active Setup\Installed Components\{7790769C-0471-11d2-AF11-00C04FA35D02}" /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Active Setup\Installed Components\{89820200-ECBD-11cf-8B85-00AA005B4340}" /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Active Setup\Installed Components\{89820200-ECBD-11cf-8B85-00AA005B4383}" /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Active Setup\Installed Components\{9381D8F2-0288-11D0-9501-00AA00B911A5}" /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Active Setup\Installed Components\{C9E9A340-D1F1-11D0-821E-444553540600}" /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Active Setup\Installed Components\{de5aed00-a4bf-11d1-9948-00c04f98bbc9}" /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Active Setup\Installed Components\{E92B03AB-B707-11d2-9CBD-0000F87A369E}" /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Active Setup\Installed Components\>{22d6f312-b0f6-11d0-94ab-0080c74c7e95}" /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Active Setup\FeatureComponentID" /V {22d6f312-b0f6-11d0-94ab-0080c74c7e95} /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Active Setup\FeatureComponentID" /V {3af36230-a269-11d1-b5bf-0000f8051515} /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Active Setup\FeatureComponentID" /V {44BBA848-CC51-11CF-AAFA-00AA00B6015C} /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Active Setup\FeatureComponentID" /V {45ea75a0-a269-11d1-b5bf-0000f8051515} /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Active Setup\FeatureComponentID" /V {4f645220-306d-11d2-995d-00c04f98bbc9} /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Active Setup\FeatureComponentID" /V {630b1da0-b465-11d1-9948-00c04f98bbc9} /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Active Setup\FeatureComponentID" /V {6BF52A52-394A-11D3-B153-00C04F79FAA6} /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Active Setup\FeatureComponentID" /V {7790769C-0471-11d2-AF11-00C04FA35D02} /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Active Setup\FeatureComponentID" /V {89820200-ECBD-11cf-8B85-00AA005B4383} /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Active Setup\FeatureComponentID" /V {9381D8F2-0288-11D0-9501-00AA00B911A5} /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Active Setup\FeatureComponentID" /V {22d6f312-b0f6-11d0-94ab-0080c74c7e95} /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Active Setup\FeatureComponentID" /V {3af36230-a269-11d1-b5bf-0000f8051515} /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Active Setup\FeatureComponentID" /V {44BBA848-CC51-11CF-AAFA-00AA00B6015C} /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Active Setup\FeatureComponentID" /V {45ea75a0-a269-11d1-b5bf-0000f8051515} /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Active Setup\FeatureComponentID" /V {4f645220-306d-11d2-995d-00c04f98bbc9} /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Active Setup\FeatureComponentID" /V {630b1da0-b465-11d1-9948-00c04f98bbc9} /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Active Setup\FeatureComponentID" /V {6BF52A52-394A-11D3-B153-00C04F79FAA6} /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Active Setup\FeatureComponentID" /V {7790769C-0471-11d2-AF11-00C04FA35D02} /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Active Setup\FeatureComponentID" /V {89820200-ECBD-11cf-8B85-00AA005B4383} /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Active Setup\FeatureComponentID" /V {9381D8F2-0288-11D0-9501-00AA00B911A5} /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Active Setup\ClsidFeature" /V {05589fa1-c356-11ce-bf01-00aa0055595a} /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Active Setup\ClsidFeature" /V {08165EA0-E946-11CF-9C87-00AA005127ED} /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Active Setup\ClsidFeature" /V {08B0E5C0-4FCB-11CF-AAA5-00401C608501} /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Active Setup\ClsidFeature" /V {2179C5D3-EBFF-11CF-B6FD-00AA00B4E220} /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Active Setup\ClsidFeature" /V {22d6f312-b0f6-11d0-94ab-0080c74c7e95} /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Active Setup\ClsidFeature" /V {25336920-03F9-11CF-8FD0-00AA00686F13} /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Active Setup\ClsidFeature" /V {333C7BC4-460F-11D0-BC04-0080C7055A83} /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Active Setup\ClsidFeature" /V {3af36230-a269-11d1-b5bf-0000f8051515} /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Active Setup\ClsidFeature" /V {7FC0B86E-5FA7-11d1-BC7C-00C04FD929DB} /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Active Setup\ClsidFeature" /V {abbe31d0-6dae-11d0-beca-00c04fd940be} /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Active Setup\ClsidFeature" /V {f5175861-2688-11d0-9c5e-00aa00a45957} /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Active Setup\ClsidFeature" /V {05589fa1-c356-11ce-bf01-00aa0055595a} /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Active Setup\ClsidFeature" /V {08165EA0-E946-11CF-9C87-00AA005127ED} /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Active Setup\ClsidFeature" /V {08B0E5C0-4FCB-11CF-AAA5-00401C608501} /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Active Setup\ClsidFeature" /V {2179C5D3-EBFF-11CF-B6FD-00AA00B4E220} /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Active Setup\ClsidFeature" /V {22d6f312-b0f6-11d0-94ab-0080c74c7e95} /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Active Setup\ClsidFeature" /V {25336920-03F9-11CF-8FD0-00AA00686F13} /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Active Setup\ClsidFeature" /V {333C7BC4-460F-11D0-BC04-0080C7055A83} /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Active Setup\ClsidFeature" /V {3af36230-a269-11d1-b5bf-0000f8051515} /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Active Setup\ClsidFeature" /V {7FC0B86E-5FA7-11d1-BC7C-00C04FD929DB} /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Active Setup\ClsidFeature" /V {abbe31d0-6dae-11d0-beca-00c04fd940be} /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Active Setup\ClsidFeature" /V {f5175861-2688-11d0-9c5e-00aa00a45957} /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\Microsoft\Active Setup\Install Check" /V IE40 /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Active Setup\Install Check" /V IE40 /F
REG DELETE "HKLM\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\WOW6432Node\Microsoft\Active Setup\MimeFeature" /V TEXT/X-VCARD /F
REG DELETE "HKLM\SOFTWARE\WOW6432Node\Microsoft\Active Setup\MimeFeature" /V TEXT/X-VCARD /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\WOW6432Node\Microsoft\Active Setup\Installed Components\{22d6f312-b0f6-11d0-94ab-0080c74c7e95}" /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\WOW6432Node\Microsoft\Active Setup\Installed Components\{2C7339CF-2B09-4501-B3F3-F3508C9228ED}" /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\WOW6432Node\Microsoft\Active Setup\Installed Components\{3af36230-a269-11d1-b5bf-0000f8051515}" /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\WOW6432Node\Microsoft\Active Setup\Installed Components\{45ea75a0-a269-11d1-b5bf-0000f8051515}" /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\WOW6432Node\Microsoft\Active Setup\Installed Components\{4f645220-306d-11d2-995d-00c04f98bbc9}" /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\WOW6432Node\Microsoft\Active Setup\Installed Components\{5fd399c0-a70a-11d1-9948-00c04f98bbc9}" /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\WOW6432Node\Microsoft\Active Setup\Installed Components\{630b1da0-b465-11d1-9948-00c04f98bbc9}" /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\WOW6432Node\Microsoft\Active Setup\Installed Components\{6BF52A52-394A-11d3-B153-00C04F79FAA6}" /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\WOW6432Node\Microsoft\Active Setup\Installed Components\{6fab99d0-bab8-11d1-994a-00c04f98bbc9}" /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\WOW6432Node\Microsoft\Active Setup\Installed Components\{7790769C-0471-11d2-AF11-00C04FA35D02}" /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\WOW6432Node\Microsoft\Active Setup\Installed Components\{89820200-ECBD-11cf-8B85-00AA005B4340}" /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\WOW6432Node\Microsoft\Active Setup\Installed Components\{89820200-ECBD-11cf-8B85-00AA005B4383}" /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\WOW6432Node\Microsoft\Active Setup\Installed Components\{9381D8F2-0288-11D0-9501-00AA00B911A5}" /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\WOW6432Node\Microsoft\Active Setup\Installed Components\{C9E9A340-D1F1-11D0-821E-444553540600}" /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\WOW6432Node\Microsoft\Active Setup\Installed Components\{de5aed00-a4bf-11d1-9948-00c04f98bbc9}" /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\WOW6432Node\Microsoft\Active Setup\Installed Components\{E92B03AB-B707-11d2-9CBD-0000F87A369E}" /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\WOW6432Node\Microsoft\Active Setup\Installed Components\>{22d6f312-b0f6-11d0-94ab-0080c74c7e95}" /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Active Setup\Installed Components\{22d6f312-b0f6-11d0-94ab-0080c74c7e95}" /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Active Setup\Installed Components\{2C7339CF-2B09-4501-B3F3-F3508C9228ED}" /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Active Setup\Installed Components\{3af36230-a269-11d1-b5bf-0000f8051515}" /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Active Setup\Installed Components\{45ea75a0-a269-11d1-b5bf-0000f8051515}" /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Active Setup\Installed Components\{4f645220-306d-11d2-995d-00c04f98bbc9}" /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Active Setup\Installed Components\{5fd399c0-a70a-11d1-9948-00c04f98bbc9}" /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Active Setup\Installed Components\{630b1da0-b465-11d1-9948-00c04f98bbc9}" /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Active Setup\Installed Components\{6BF52A52-394A-11d3-B153-00C04F79FAA6}" /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Active Setup\Installed Components\{6fab99d0-bab8-11d1-994a-00c04f98bbc9}" /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Active Setup\Installed Components\{7790769C-0471-11d2-AF11-00C04FA35D02}" /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Active Setup\Installed Components\{89820200-ECBD-11cf-8B85-00AA005B4340}" /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Active Setup\Installed Components\{89820200-ECBD-11cf-8B85-00AA005B4383}" /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Active Setup\Installed Components\{9381D8F2-0288-11D0-9501-00AA00B911A5}" /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Active Setup\Installed Components\{C9E9A340-D1F1-11D0-821E-444553540600}" /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Active Setup\Installed Components\{de5aed00-a4bf-11d1-9948-00c04f98bbc9}" /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Active Setup\Installed Components\{E92B03AB-B707-11d2-9CBD-0000F87A369E}" /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Active Setup\Installed Components\>{22d6f312-b0f6-11d0-94ab-0080c74c7e95}" /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\WOW6432Node\Microsoft\Active Setup\FeatureComponentID" /V {22d6f312-b0f6-11d0-94ab-0080c74c7e95} /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\WOW6432Node\Microsoft\Active Setup\FeatureComponentID" /V {3af36230-a269-11d1-b5bf-0000f8051515} /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\WOW6432Node\Microsoft\Active Setup\FeatureComponentID" /V {44BBA848-CC51-11CF-AAFA-00AA00B6015C} /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\WOW6432Node\Microsoft\Active Setup\FeatureComponentID" /V {45ea75a0-a269-11d1-b5bf-0000f8051515} /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\WOW6432Node\Microsoft\Active Setup\FeatureComponentID" /V {4f645220-306d-11d2-995d-00c04f98bbc9} /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\WOW6432Node\Microsoft\Active Setup\FeatureComponentID" /V {630b1da0-b465-11d1-9948-00c04f98bbc9} /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\WOW6432Node\Microsoft\Active Setup\FeatureComponentID" /V {6BF52A52-394A-11D3-B153-00C04F79FAA6} /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\WOW6432Node\Microsoft\Active Setup\FeatureComponentID" /V {7790769C-0471-11d2-AF11-00C04FA35D02} /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\WOW6432Node\Microsoft\Active Setup\FeatureComponentID" /V {89820200-ECBD-11cf-8B85-00AA005B4383} /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\WOW6432Node\Microsoft\Active Setup\FeatureComponentID" /V {9381D8F2-0288-11D0-9501-00AA00B911A5} /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Active Setup\FeatureComponentID" /V {22d6f312-b0f6-11d0-94ab-0080c74c7e95} /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Active Setup\FeatureComponentID" /V {3af36230-a269-11d1-b5bf-0000f8051515} /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Active Setup\FeatureComponentID" /V {44BBA848-CC51-11CF-AAFA-00AA00B6015C} /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Active Setup\FeatureComponentID" /V {45ea75a0-a269-11d1-b5bf-0000f8051515} /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Active Setup\FeatureComponentID" /V {4f645220-306d-11d2-995d-00c04f98bbc9} /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Active Setup\FeatureComponentID" /V {630b1da0-b465-11d1-9948-00c04f98bbc9} /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Active Setup\FeatureComponentID" /V {6BF52A52-394A-11D3-B153-00C04F79FAA6} /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Active Setup\FeatureComponentID" /V {7790769C-0471-11d2-AF11-00C04FA35D02} /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Active Setup\FeatureComponentID" /V {89820200-ECBD-11cf-8B85-00AA005B4383} /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Active Setup\FeatureComponentID" /V {9381D8F2-0288-11D0-9501-00AA00B911A5} /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\WOW6432Node\Microsoft\Active Setup\ClsidFeature" /V {05589fa1-c356-11ce-bf01-00aa0055595a} /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\WOW6432Node\Microsoft\Active Setup\ClsidFeature" /V {08165EA0-E946-11CF-9C87-00AA005127ED} /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\WOW6432Node\Microsoft\Active Setup\ClsidFeature" /V {08B0E5C0-4FCB-11CF-AAA5-00401C608501} /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\WOW6432Node\Microsoft\Active Setup\ClsidFeature" /V {2179C5D3-EBFF-11CF-B6FD-00AA00B4E220} /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\WOW6432Node\Microsoft\Active Setup\ClsidFeature" /V {22d6f312-b0f6-11d0-94ab-0080c74c7e95} /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\WOW6432Node\Microsoft\Active Setup\ClsidFeature" /V {25336920-03F9-11CF-8FD0-00AA00686F13} /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\WOW6432Node\Microsoft\Active Setup\ClsidFeature" /V {333C7BC4-460F-11D0-BC04-0080C7055A83} /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\WOW6432Node\Microsoft\Active Setup\ClsidFeature" /V {3af36230-a269-11d1-b5bf-0000f8051515} /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\WOW6432Node\Microsoft\Active Setup\ClsidFeature" /V {7FC0B86E-5FA7-11d1-BC7C-00C04FD929DB} /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\WOW6432Node\Microsoft\Active Setup\ClsidFeature" /V {abbe31d0-6dae-11d0-beca-00c04fd940be} /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\WOW6432Node\Microsoft\Active Setup\ClsidFeature" /V {f5175861-2688-11d0-9c5e-00aa00a45957} /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Active Setup\ClsidFeature" /V {05589fa1-c356-11ce-bf01-00aa0055595a} /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Active Setup\ClsidFeature" /V {08165EA0-E946-11CF-9C87-00AA005127ED} /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Active Setup\ClsidFeature" /V {08B0E5C0-4FCB-11CF-AAA5-00401C608501} /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Active Setup\ClsidFeature" /V {2179C5D3-EBFF-11CF-B6FD-00AA00B4E220} /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Active Setup\ClsidFeature" /V {22d6f312-b0f6-11d0-94ab-0080c74c7e95} /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Active Setup\ClsidFeature" /V {25336920-03F9-11CF-8FD0-00AA00686F13} /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Active Setup\ClsidFeature" /V {333C7BC4-460F-11D0-BC04-0080C7055A83} /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Active Setup\ClsidFeature" /V {3af36230-a269-11d1-b5bf-0000f8051515} /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Active Setup\ClsidFeature" /V {7FC0B86E-5FA7-11d1-BC7C-00C04FD929DB} /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Active Setup\ClsidFeature" /V {abbe31d0-6dae-11d0-beca-00c04fd940be} /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Active Setup\ClsidFeature" /V {f5175861-2688-11d0-9c5e-00aa00a45957} /F
REG DELETE "HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SOFTWARE\WOW6432Node\Microsoft\Active Setup\Install Check" /V IE40 /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Active Setup\Install Check" /V IE40 /F
ECHO -------
REG DELETE HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SYSTEM\ControlSet001\Control\WMI /F
REG DELETE HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SYSTEM\ControlSet001\Control\WMI\AUTOLOGGER /F
REG DELETE HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SYSTEM\ControlSet001\Control\WMI\GLOBALLOGGER /F
REG DELETE HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SYSTEM\ControlSet001\Control\WMI\SECURITY /F
REG ADD HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SYSTEM\ControlSet001\Control\WMI /F
REG ADD HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SYSTEM\ControlSet001\Control\WMI\AUTOLOGGER /F
REG ADD HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SYSTEM\ControlSet001\Control\WMI\GLOBALLOGGER /F
REG ADD HKEY_LOCAL_MACHINE\{bf1a281b-ad7b-4476-ac95-f47682990ce7}C:/Windows/System32/config/SYSTEM\ControlSet001\Control\WMI\SECURITY /F
REG DELETE HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Control\WMI /F
REG DELETE HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Control\WMI\AUTOLOGGER /F
REG DELETE HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Control\WMI\GLOBALLOGGER /F
REG DELETE HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Control\WMI\SECURITY /F
REG ADD HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Control\WMI /F
REG ADD HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Control\WMI\AUTOLOGGER /F
REG ADD HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Control\WMI\GLOBALLOGGER /F
REG ADD HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Control\WMI\SECURITY /F
EXIT
